//请求数据
export const GET_SUBSCRIPTION_LIST_SUCCESS = 'GET_SUBSCRIPTION_LIST_SUCCESS'
//异常
export const GET_SUBSCRIPTION_LIST_ERR = 'GET_SUBSCRIPTION_LIST_ERR'
// 正在请求
export const GET_SUBSCRIPTION_LIST_ING = 'GET_SUBSCRIPTION_LIST_ING'
